import type { Recipe } from '@/types'

export const SAMPLE_RECIPES: Recipe[] = [
  {
    id: 'r1',
    name: 'Spaghetti Aglio e Olio',
    description: 'A classic Italian pasta dish with garlic, olive oil, and chili flakes. Simple, bold, and satisfying.',
    ingredients: [
      { name: 'spaghetti', quantity: 400, unit: 'g' },
      { name: 'garlic', quantity: 6, unit: 'cloves' },
      { name: 'olive oil', quantity: 80, unit: 'ml' },
      { name: 'red chili flakes', quantity: 1, unit: 'tsp' },
      { name: 'parsley', quantity: 1, unit: 'bunch' },
      { name: 'parmesan', quantity: 50, unit: 'g', optional: true },
      { name: 'salt', quantity: 1, unit: 'tsp' },
      { name: 'black pepper', quantity: 0.5, unit: 'tsp' },
    ],
    instructions: [
      'Bring a large pot of salted water to boil and cook spaghetti until al dente.',
      'While pasta cooks, thinly slice garlic and heat olive oil in a large pan over medium-low heat.',
      'Add garlic to oil and cook gently until golden — about 3 minutes. Do not burn it.',
      'Add chili flakes, stir for 30 seconds.',
      'Reserve 1 cup pasta water, then drain pasta and add to the pan.',
      'Toss vigorously, adding pasta water as needed to create a silky sauce.',
      'Stir in parsley, season, and serve immediately with parmesan.',
    ],
    cooking_time: 20,
    prep_time: 5,
    servings: 4,
    difficulty: 'easy',
    dietary_tags: ['vegetarian', 'vegan'],
    cuisine: 'Italian',
    image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'r2',
    name: 'Chicken Stir-Fry',
    description: 'A quick weeknight stir-fry loaded with vegetables and tender chicken in a savory soy-ginger sauce.',
    ingredients: [
      { name: 'chicken breast', quantity: 500, unit: 'g' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'ginger', quantity: 1, unit: 'tsp' },
      { name: 'bell pepper', quantity: 2, unit: 'pcs' },
      { name: 'broccoli', quantity: 200, unit: 'g' },
      { name: 'sesame oil', quantity: 1, unit: 'tbsp' },
      { name: 'cornstarch', quantity: 2, unit: 'tbsp' },
      { name: 'vegetable oil', quantity: 2, unit: 'tbsp' },
      { name: 'spring onions', quantity: 3, unit: 'pcs' },
    ],
    instructions: [
      'Slice chicken into thin strips and toss with cornstarch, 1 tbsp soy sauce, and a pinch of salt.',
      'Mix remaining soy sauce, ginger, garlic and sesame oil in a bowl for the sauce.',
      'Heat oil in a wok over high heat until smoking.',
      'Add chicken and cook for 3-4 minutes until golden. Remove and set aside.',
      'Add vegetables to wok and stir-fry for 3 minutes.',
      'Return chicken, pour over sauce, and toss everything together for 1 minute.',
      'Serve immediately over rice, garnished with spring onions.',
    ],
    cooking_time: 20,
    prep_time: 15,
    servings: 4,
    difficulty: 'easy',
    dietary_tags: ['gluten-free option', 'high-protein'],
    cuisine: 'Asian',
    image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'r3',
    name: 'Classic Tomato Soup',
    description: 'Velvety, rich tomato soup made from canned tomatoes. Pairs beautifully with crusty bread.',
    ingredients: [
      { name: 'canned tomatoes', quantity: 800, unit: 'g' },
      { name: 'onion', quantity: 1, unit: 'pcs' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'vegetable stock', quantity: 500, unit: 'ml' },
      { name: 'cream', quantity: 100, unit: 'ml', optional: true },
      { name: 'basil', quantity: 1, unit: 'bunch' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
      { name: 'sugar', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Dice onion and mince garlic. Sauté in olive oil over medium heat for 5 minutes until soft.',
      'Add canned tomatoes, stock, salt, and sugar. Simmer for 20 minutes.',
      'Blend until completely smooth using a stick blender.',
      'Stir in cream if using, and fresh basil.',
      'Adjust seasoning and serve hot.',
    ],
    cooking_time: 30,
    prep_time: 10,
    servings: 4,
    difficulty: 'easy',
    dietary_tags: ['vegetarian', 'vegan', 'gluten-free'],
    cuisine: 'European',
    image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'r4',
    name: 'Shakshuka',
    description: 'Eggs poached in a spiced tomato and pepper sauce. A hearty one-pan breakfast or dinner.',
    ingredients: [
      { name: 'eggs', quantity: 4, unit: 'pcs' },
      { name: 'canned tomatoes', quantity: 400, unit: 'g' },
      { name: 'bell pepper', quantity: 1, unit: 'pcs' },
      { name: 'onion', quantity: 1, unit: 'pcs' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'cumin', quantity: 1, unit: 'tsp' },
      { name: 'paprika', quantity: 1, unit: 'tsp' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'fresh parsley', quantity: 1, unit: 'bunch' },
      { name: 'feta cheese', quantity: 80, unit: 'g', optional: true },
    ],
    instructions: [
      'Dice onion and pepper. Sauté in olive oil for 5 minutes.',
      'Add garlic, cumin and paprika. Cook 1 minute until fragrant.',
      'Pour in tomatoes, season well, and simmer 10 minutes.',
      'Make wells in the sauce and crack in eggs.',
      'Cover and cook 6-8 minutes until whites are set but yolks are still runny.',
      'Top with crumbled feta and parsley. Serve with crusty bread.',
    ],
    cooking_time: 25,
    prep_time: 10,
    servings: 2,
    difficulty: 'easy',
    dietary_tags: ['vegetarian', 'gluten-free'],
    cuisine: 'Middle Eastern',
    image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'r5',
    name: 'Lentil Dal',
    description: 'A warming Indian dal with red lentils, tomatoes, and aromatic spices. Perfect over basmati rice.',
    ingredients: [
      { name: 'red lentils', quantity: 250, unit: 'g' },
      { name: 'canned tomatoes', quantity: 400, unit: 'g' },
      { name: 'onion', quantity: 1, unit: 'pcs' },
      { name: 'garlic', quantity: 4, unit: 'cloves' },
      { name: 'ginger', quantity: 1, unit: 'tsp' },
      { name: 'cumin', quantity: 1, unit: 'tsp' },
      { name: 'turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'garam masala', quantity: 1, unit: 'tsp' },
      { name: 'vegetable stock', quantity: 700, unit: 'ml' },
      { name: 'coconut milk', quantity: 200, unit: 'ml' },
      { name: 'spinach', quantity: 100, unit: 'g', optional: true },
    ],
    instructions: [
      'Rinse lentils and set aside.',
      'Sauté diced onion in oil for 5 minutes. Add garlic and ginger, cook 2 more minutes.',
      'Add all spices, stir and cook 1 minute.',
      'Add lentils, tomatoes and stock. Bring to boil then simmer 20 minutes until lentils are soft.',
      'Stir in coconut milk and spinach if using. Simmer 5 more minutes.',
      'Adjust seasoning and serve over rice with naan.',
    ],
    cooking_time: 35,
    prep_time: 10,
    servings: 4,
    difficulty: 'easy',
    dietary_tags: ['vegan', 'vegetarian', 'gluten-free', 'high-protein'],
    cuisine: 'Indian',
    image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'r6',
    name: 'Greek Salad',
    description: 'Fresh, crisp and tangy. The only salad that needs no cooking — just chopping and dressing.',
    ingredients: [
      { name: 'cucumber', quantity: 1, unit: 'pcs' },
      { name: 'tomatoes', quantity: 3, unit: 'pcs' },
      { name: 'red onion', quantity: 0.5, unit: 'pcs' },
      { name: 'olives', quantity: 100, unit: 'g' },
      { name: 'feta cheese', quantity: 150, unit: 'g' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp' },
      { name: 'oregano', quantity: 1, unit: 'tsp' },
      { name: 'lemon juice', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Chop cucumber, tomatoes and red onion into chunky pieces.',
      'Combine in a large bowl with olives.',
      'Crumble feta over the top.',
      'Dress with olive oil, lemon juice and oregano.',
      'Season and serve immediately.',
    ],
    cooking_time: 0,
    prep_time: 10,
    servings: 2,
    difficulty: 'easy',
    dietary_tags: ['vegetarian', 'gluten-free', 'keto'],
    cuisine: 'Greek',
    image_url: null,
    created_at: new Date().toISOString(),
  },
]

export const CATEGORIES = [
  'produce', 'dairy', 'meat', 'seafood', 'grains',
  'canned', 'frozen', 'beverages', 'condiments',
  'snacks', 'baking', 'spices', 'other',
] as const

export const UNITS = [
  'g', 'kg', 'ml', 'l', 'tsp', 'tbsp', 'cup',
  'oz', 'lb', 'pcs', 'bunch', 'slice', 'can',
  'bag', 'box', 'bottle', 'pack',
] as const

export const DIETARY_OPTIONS = [
  'vegetarian', 'vegan', 'gluten-free', 'dairy-free',
  'keto', 'paleo', 'halal', 'kosher', 'low-carb',
  'high-protein', 'low-sodium',
]

export const ALLERGY_OPTIONS = [
  'peanuts', 'tree nuts', 'dairy', 'eggs', 'wheat',
  'soy', 'fish', 'shellfish', 'sesame',
]

export const COOKBOOK_CATEGORIES = [
  'General Cooking',
  'Healthy Cooking',
  'Meal Prep',
  'Beginner Cooking',
  'Dietary-Specific',
]
